### ISSUE TITLE
The authorisation method you have provided is not supported

### ISSUE THREAD

**Issue by absoludity** [go-amz/amz#22]
I'm testing the readiness of deployments to cn-north-1. The stream data was fixed yesterday (great - https://github.com/go-amz/amz/issues/21), but when bootstrapping now, I get the error:

2015-01-28 02:00:39 ERROR juju.cmd supercommand.go:323 cannot determine if environment is already bootstrapped.: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

It's worth noting that accessing cn-north-1 via the awscli works without issue (as far as I tested): https://pastebin.canonical.com/124392/

More details: https://pastebin.canonical.com/124394/

**Comment by axw** [comment]
It appears that the V4 signing method was added to the aws package, but the s3 package has its own version of signing that wasn't updated.

**Comment by kat-co** [comment]
I'm going to close this issue so that we have a single point of reference for tracking bug information. For interested parties, you can find the latest here: https://bugs.launchpad.net/juju-core/+bug/1415693.
