### ISSUE TITLE
`s3.Bucket.SignedURL()` generates incorrect `X-Amz-Date` if the server is not on UTC.

### ISSUE THREAD

**Issue by ben181231** [go-amz/amz#69]
### Expected Results

When server running on UTC+8 timezone and current time is `Thu, 18 Aug 2016 08:12:34 UTC+8`, the generated `X-Amz-Date` should be `20160818T001234Z`.
### Actual Results

Currently, the result is `20160818T081234Z`. A `403` response will be received when following the generated URL.

**Comment by axw** [comment]
Fixed by #70.
